sudo: required

language: python

services:
  - docker

env:
  - toolset_branch: F_travis_ci_support
  - server_type: travis
  - used_modules: check_cache,code_coverage
  - remote_shell_script: 'https://raw.githubusercontent.com/shadow-robot/sr-build-tools/$toolset_branch/bin/sr-run-ci-build.sh'

script:
- curl -s "$( echo "$remote_shell_script" | sed 's/#/%23/g' )" | bash /dev/stdin "$toolset_branch" $server_type $used_modules
